services:
  redis-cluster-node1:
    image: redis/redis-stack-server:latest
    container_name: cluster-node1
    restart: unless-stopped
    command: >
      redis-server
      --port 6379
      --dir /data 
      --save 60 1 
      --appendonly yes 
      --protected-mode no 
      --cluster-enabled yes
      --loadmodule /opt/redis-stack/lib/rejson.so
      --notify-keyspace-events AKE
    ports:
      - 6379:6379
    volumes:
      - node1:/data
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.2
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "PING"]
      interval: 10s
      retries: 5

  redis-cluster-node2:
    image: redis/redis-stack-server:latest
    container_name: cluster-node2
    restart: unless-stopped
    command: >
      redis-server
      --port 6380
      --dir /data 
      --save 60 1 
      --appendonly yes 
      --protected-mode no 
      --cluster-enabled yes
      --loadmodule /opt/redis-stack/lib/rejson.so
      --notify-keyspace-events AKE
    ports:
      - 6380:6380
    volumes:
      - node2:/data
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.3
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6380", "PING"]
      interval: 10s
      retries: 5

  redis-cluster-node3:
    image: redis/redis-stack-server:latest
    container_name: cluster-node3
    restart: unless-stopped
    command: >
      redis-server
      --port 6381
      --dir /data
      --save 60 1
      --appendonly yes
      --protected-mode no
      --cluster-enabled yes
      --loadmodule /opt/redis-stack/lib/rejson.so
      --notify-keyspace-events AKE
    ports:
      - 6381:6381
    volumes:
      - node3:/data
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.4
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6381", "PING"]
      interval: 10s
      retries: 5

  redis-cluster-node4:
    image: redis/redis-stack-server:latest
    container_name: cluster-node4
    restart: unless-stopped
    command: >
      redis-server
      --dir /data
      --port 6382
      --save 60 1
      --appendonly yes
      --protected-mode no
      --cluster-enabled yes
      --loadmodule /opt/redis-stack/lib/rejson.so
      --notify-keyspace-events AKE
    ports:
      - 6382:6382
    volumes:
      - node4:/data
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.5
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6382", "PING"]
      interval: 10s
      retries: 5

  redis-cluster-node5:
    image: redis/redis-stack-server:latest
    container_name: cluster-node5
    restart: unless-stopped
    command: >
      redis-server
      --port 6383
      --dir /data
      --save 60 1
      --appendonly yes
      --protected-mode no
      --cluster-enabled yes
      --loadmodule /opt/redis-stack/lib/rejson.so
      --notify-keyspace-events AKE
    ports:
      - 6383:6383
    volumes:
      - node5:/data
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.6
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6383", "PING"]
      interval: 10s
      retries: 5

  redis-cluster-node6:
    image: redis/redis-stack-server:latest
    container_name: cluster-node6
    restart: unless-stopped
    command: >
      redis-server
      --port 6384
      --dir /data
      --save 60 1
      --appendonly yes
      --protected-mode no
      --cluster-enabled yes
      --loadmodule /opt/redis-stack/lib/rejson.so
      --notify-keyspace-events AKE
    ports:
      - 6384:6384
    volumes:
      - node6:/data
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.7
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6384", "PING"]
      interval: 10s
      retries: 5

  redis-cluster-init:
    image: redis/redis-stack-server:latest
    container_name: cluster-node-init
    restart: "no"
    command: >
      sh -c "/init.sh"
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.8
    volumes:
      - ./init.sh/:/init.sh
    depends_on:
      redis-cluster-node1:
        condition: service_healthy
      redis-cluster-node2:
        condition: service_healthy
      redis-cluster-node3:
        condition: service_healthy
      redis-cluster-node4:
        condition: service_healthy
      redis-cluster-node5:
        condition: service_healthy
      redis-cluster-node6:
        condition: service_healthy

  redis-insight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    container_name: redisinsight
    ports:
      - 5540:5540
    volumes:
      - redis-insight:/data
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.9

volumes:
  node1:
  node2:
  node3:
  node4:
  node5:
  node6:
  redis-insight:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
